### ISSUE TITLE
Error while running compile_process.py

### ISSUE THREAD

**Issue by waleeds1** [bogdanvuk/bdp#1]
I am trying to run the compile_process.py file provided as an example but am getting this error 
```Traceback (most recent call last):
  File "/usr/local/bin/bdp", line 8, in <module>
    sys.exit(main())
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/render.py", line 212, in main
    render(opts.input, opts.output, None, options)
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/render.py", line 172, in render
    fig = render_tikz(fin)
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/render.py", line 43, in render_tikz
    bdp_mod = loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 962, in load_module
  File "<frozen importlib._bootstrap_external>", line 787, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "diag.py", line 7, in <module>
    fig << block(r"Python \\ Description")
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/figure.py", line 114, in __lshift__
    self.add(val)
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/group.py", line 50, in add
    self.__setitem__(key, obj)
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/figure.py", line 123, in __setitem__
    self._tikz += val._render_tikz(self)
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/node.py", line 681, in _render_tikz
    xallign_self = self.nx(0.0)
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/node.py", line 204, in coord
    return func(self, pos, grid)
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/node.py", line 376, in nx
    return self.n(pos, 0, grid)[0]
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/node.py", line 471, in n
    pos = super().n(p1, p2, grid)
  File "/home/waleeds1/.local/lib/python3.8/site-packages/bdp/node.py", line 163, in coord
    pos[i] *= self.size[i]
TypeError: unsupported operand type(s) for *=: 'float' and 'NoneType'```

**Comment by nicolube** [comment]
Same issue for me
